#pragma once

#define LIBIRCCLIENT_VER_MAJOR 2
#define LIBIRCCLIENT_VER_MINOR 0
#define LIBIRCCLIENT_VER_PATCH 0

#define LIBIRCCLIENT_VERSION (LIBIRCCLIENT_VER_MAJOR * 10000 + LIBIRCCLIENT_VER_MINOR * 100 + LIBIRCCLIENT_VER_PATCH)
